// device-info-example/app/components/Home.vue
<template>
    <Page>
        <ActionBar>
            <Label text="DeviceInfo example"/>
        </ActionBar>
        <FlexboxLayout class="container">
            <Label class="info" :text="name"/>

            <Label class="info" :text="version"/>

            <Label class="info" :text="carrier"/>
        </FlexboxLayout>
    </Page>
</template>

<script>
  import { getApplicationName, getVersion, getCarrierSync } from "react-native-device-info";
  export default {
    computed: {
      name() {
        return "App name:" + getApplicationName();
      },
      version() {
        return "App version:" + getVersion();
      },
      carrier() {
        return "Carrier:" + getCarrierSync()
      }
    }
  };
</script>

<style scoped lang="scss">
    @import '@nativescript/theme/scss/variables/blue';

    // Custom styles
    .fas {
        @include colorize($color: accent);
    }

    .info {
        font-size: 20;
        margin-bottom: 10;
    }

    .container {
        flex-direction: column;
        justify-content: center;
        align-items: center;
        width: 100%;
    }
</style>

// gzip-example/app/components/Home.svelte
<page>
    <actionBar title="Gzip example" />
    <flexboxLayout class="info">
        <button
            text="Compress string to base64"
            class='btn'
            on:tap={compress}
        />
        <label textWrap="true" class="label" text={compressed} />

        <button
            text="Decompress base64 string"
            class='btn'
            on:tap={decompress}
        />
        <label class="label" text={decompressed} />
    </flexboxLayout>
</page>

<script lang="ts">
    import { deflate, inflate } from 'react-native-gzip';
    let compressed = "";
    let decompressed = "";

    const compress = async () => {
        compressed = await deflate("NativeScript is awesome");
    }

    const decompress = async () => {
        if (compressed) {
            decompressed = await inflate(compressed);
        }
    }
</script>

<style>
    .btn {
        background-color: coral;
        padding: 0 20;
        color: white;
        border-radius: 100;
        width: 300;
    }
    .label {
        font-size: 16;
        max-width: 300;
    }
    .info {
        font-size: 20;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        flex-wrap: wrap;
        padding: 20;
    }
</style>
